export const group: { [key: string]: { label: string; value: string }[] } = {
  Безопасность: [
    { value: '31', label: 'ян' },
    { value: '68', label: 'фе' },
    { value: '12', label: 'ма' },
    { value: '45', label: 'ап' },
    { value: '25', label: 'ма' },
    { value: '56', label: 'ию' },
    { value: '21', label: 'ил' },
    { value: '11', label: 'ав' },
    { value: '19', label: 'се' },
    { value: '30', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '33', label: 'де' },
  ],
  Благоустройство: [
    { value: '15', label: 'ян' },
    { value: '17', label: 'фе' },
    { value: '9', label: 'ма' },
    { value: '14', label: 'ап' },
    { value: '30', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '29', label: 'ил' },
    { value: '45', label: 'ав' },
    { value: '50', label: 'се' },
    { value: '22', label: 'ок' },
    { value: '14', label: 'но' },
    { value: '67', label: 'де' },
  ],

  ЖКХ: [
    { value: '40', label: 'ян' },
    { value: '35', label: 'фе' },
    { value: '20', label: 'ма' },
    { value: '5', label: 'ап' },
    { value: '1', label: 'ма' },
    { value: '14', label: 'ию' },
    { value: '22', label: 'ил' },
    { value: '30', label: 'ав' },
    { value: '36', label: 'се' },
    { value: '42', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '70', label: 'де' },
  ],

  'Связь и телевидение': [
    { value: '25', label: 'ян' },
    { value: '17', label: 'фе' },
    { value: '23', label: 'ма' },
    { value: '31', label: 'ап' },
    { value: '46', label: 'ма' },
    { value: '12', label: 'ию' },
    { value: '25', label: 'ил' },
    { value: '36', label: 'ав' },
    { value: '12', label: 'се' },
    { value: '75', label: 'ок' },
    { value: '34', label: 'но' },
    { value: '70', label: 'де' },
  ],
  Дороги: [
    { value: '20', label: 'ян' },
    { value: '15', label: 'фе' },
    { value: '22', label: 'ма' },
    { value: '34', label: 'ап' },
    { value: '15', label: 'ма' },
    { value: '7', label: 'ию' },
    { value: '8', label: 'ил' },
    { value: '9', label: 'ав' },
    { value: '13', label: 'се' },
    { value: '17', label: 'ок' },
    { value: '33', label: 'но' },
    { value: '40', label: 'де' },
  ],

  Торговля: [
    { value: '35', label: 'ян' },
    { value: '76', label: 'фе' },
    { value: '67', label: 'ма' },
    { value: '53', label: 'ап' },
    { value: '67', label: 'ма' },
    { value: '13', label: 'ию' },
    { value: '34', label: 'ил' },
    { value: '45', label: 'ав' },
    { value: '63', label: 'се' },
    { value: '34', label: 'ок' },
    { value: '65', label: 'но' },
    { value: '76', label: 'де' },
  ],
  'Здравоохранение/Медицина': [
    { value: '25', label: 'ян' },
    { value: '30', label: 'фе' },
    { value: '14', label: 'ма' },
    { value: '29', label: 'ап' },
    { value: '44', label: 'ма' },
    { value: '60', label: 'ию' },
    { value: '45', label: 'ил' },
    { value: '36', label: 'ав' },
    { value: '29', label: 'се' },
    { value: '19', label: 'ок' },
    { value: '37', label: 'но' },
    { value: '13', label: 'де' },
  ],

  'Мусор/Свалки/ТКО': [
    { value: '44', label: 'ян' },
    { value: '30', label: 'фе' },
    { value: '20', label: 'ма' },
    { value: '15', label: 'ап' },
    { value: '13', label: 'ма' },
    { value: '17', label: 'ию' },
    { value: '22', label: 'ил' },
    { value: '36', label: 'ав' },
    { value: '56', label: 'се' },
    { value: '34', label: 'ок' },
    { value: '22', label: 'но' },
    { value: '39', label: 'де' },
  ],
  Электроснабжение: [
    { value: '13', label: 'ян' },
    { value: '65', label: 'фе' },
    { value: '35', label: 'ма' },
    { value: '65', label: 'ап' },
    { value: '34', label: 'ма' },
    { value: '34', label: 'ию' },
    { value: '12', label: 'ил' },
    { value: '32', label: 'ав' },
    { value: '65', label: 'се' },
    { value: '45', label: 'ок' },
    { value: '44', label: 'но' },
    { value: '31', label: 'де' },
  ],

  'Социальное обслуживание и защита': [
    { value: '4', label: 'ян' },
    { value: '7', label: 'фе' },
    { value: '12', label: 'ма' },
    { value: '10', label: 'ап' },
    { value: '21', label: 'ма' },
    { value: '3', label: 'ию' },
    { value: '2', label: 'ил' },
    { value: '45', label: 'ав' },
    { value: '65', label: 'се' },
    { value: '30', label: 'ок' },
    { value: '25', label: 'но' },
    { value: '20', label: 'де' },
  ],

  Образование: [
    { value: '8', label: 'ян' },
    { value: '5', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '10', label: 'ап' },
    { value: '14', label: 'ма' },
    { value: '38', label: 'ию' },
    { value: '35', label: 'ил' },
    { value: '60', label: 'ав' },
    { value: '55', label: 'се' },
    { value: '22', label: 'ок' },
    { value: '10', label: 'но' },
    { value: '3', label: 'де' },
  ],

  'Газ и топливо': [
    { value: '34', label: 'ян' },
    { value: '67', label: 'фе' },
    { value: '87', label: 'ма' },
    { value: '74', label: 'ап' },
    { value: '76', label: 'ма' },
    { value: '54', label: 'ию' },
    { value: '34', label: 'ил' },
    { value: '56', label: 'ав' },
    { value: '12', label: 'се' },
    { value: '64', label: 'ок' },
    { value: '87', label: 'но' },
    { value: '32', label: 'де' },
  ],
  Экология: [
    { value: '12', label: 'ян' },
    { value: '21', label: 'фе' },
    { value: '31', label: 'ма' },
    { value: '35', label: 'ап' },
    { value: '21', label: 'ма' },
    { value: '27', label: 'ию' },
    { value: '28', label: 'ил' },
    { value: '15', label: 'ав' },
    { value: '23', label: 'се' },
    { value: '64', label: 'ок' },
    { value: '65', label: 'но' },
    { value: '12', label: 'де' },
  ],
  "МФЦ 'Мои документы'": [
    { value: '34', label: 'ян' },
    { value: '54', label: 'фе' },
    { value: '36', label: 'ма' },
    { value: '12', label: 'ап' },
    { value: '65', label: 'ма' },
    { value: '34', label: 'ию' },
    { value: '54', label: 'ил' },
    { value: '61', label: 'ав' },
    { value: '35', label: 'се' },
    { value: '24', label: 'ок' },
    { value: '56', label: 'но' },
    { value: '35', label: 'де' },
  ],
  'Общественный транспорт': [
    { value: '40', label: 'ян' },
    { value: '45', label: 'фе' },
    { value: '12', label: 'ма' },
    { value: '7', label: 'ап' },
    { value: '31', label: 'ма' },
    { value: '23', label: 'ию' },
    { value: '25', label: 'ил' },
    { value: '27', label: 'ав' },
    { value: '9', label: 'се' },
    { value: '18', label: 'ок' },
    { value: '33', label: 'но' },
    { value: '34', label: 'де' },
  ],

  Коронавирус: [
    { value: '63', label: 'ян' },
    { value: '60', label: 'фе' },
    { value: '56', label: 'ма' },
    { value: '43', label: 'ап' },
    { value: '22', label: 'ма' },
    { value: '30', label: 'ию' },
    { value: '28', label: 'ил' },
    { value: '23', label: 'ав' },
    { value: '44', label: 'се' },
    { value: '33', label: 'ок' },
    { value: '70', label: 'но' },
    { value: '67', label: 'де' },
  ],
  Мобилизация: [
    { value: '34', label: 'ян' },
    { value: '31', label: 'фе' },
    { value: '16', label: 'ма' },
    { value: '54', label: 'ап' },
    { value: '23', label: 'ма' },
    { value: '53', label: 'ию' },
    { value: '23', label: 'ил' },
    { value: '65', label: 'ав' },
    { value: '12', label: 'се' },
    { value: '54', label: 'ок' },
    { value: '33', label: 'но' },
    { value: '24', label: 'де' },
  ],
  Роспотребнадзор: [
    { value: '56', label: 'ян' },
    { value: '13', label: 'фе' },
    { value: '25', label: 'ма' },
    { value: '63', label: 'ап' },
    { value: '14', label: 'ма' },
    { value: '53', label: 'ию' },
    { value: '23', label: 'ил' },
    { value: '13', label: 'ав' },
    { value: '53', label: 'се' },
    { value: '46', label: 'ок' },
    { value: '13', label: 'но' },
    { value: '75', label: 'де' },
  ],
  'Памятники и объекты культурного наследия': [
    { value: '35', label: 'ян' },
    { value: '13', label: 'фе' },
    { value: '52', label: 'ма' },
    { value: '54', label: 'ап' },
    { value: '30', label: 'ма' },
    { value: '20', label: 'ию' },
    { value: '40', label: 'ил' },
    { value: '15', label: 'ав' },
    { value: '52', label: 'се' },
    { value: '53', label: 'ок' },
    { value: '36', label: 'но' },
    { value: '31', label: 'де' },
  ],
  'Погребение и похоронное дело': [
    { value: '25', label: 'ян' },
    { value: '75', label: 'фе' },
    { value: '12', label: 'ма' },
    { value: '64', label: 'ап' },
    { value: '14', label: 'ма' },
    { value: '63', label: 'ию' },
    { value: '23', label: 'ил' },
    { value: '57', label: 'ав' },
    { value: '23', label: 'се' },
    { value: '65', label: 'ок' },
    { value: '25', label: 'но' },
    { value: '63', label: 'де' },
  ],
  'Государственная собственность': [
    { value: '46', label: 'ян' },
    { value: '13', label: 'фе' },
    { value: '36', label: 'ма' },
    { value: '74', label: 'ап' },
    { value: '23', label: 'ма' },
    { value: '36', label: 'ию' },
    { value: '24', label: 'ил' },
    { value: '21', label: 'ав' },
    { value: '35', label: 'се' },
    { value: '47', label: 'ок' },
    { value: '63', label: 'но' },
    { value: '23', label: 'де' },
  ],
  'Физическая культура и спорт': [
    { value: '43', label: 'ян' },
    { value: '12', label: 'фе' },
    { value: '35', label: 'ма' },
    { value: '64', label: 'ап' },
    { value: '23', label: 'ма' },
    { value: '43', label: 'ию' },
    { value: '41', label: 'ил' },
    { value: '25', label: 'ав' },
    { value: '34', label: 'се' },
    { value: '53', label: 'ок' },
    { value: '41', label: 'но' },
    { value: '23', label: 'де' },
  ],
  'Строительство и архитектура': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  Спецпроекты: [
    { value: '46', label: 'ян' },
    { value: '21', label: 'фе' },
    { value: '64', label: 'ма' },
    { value: '41', label: 'ап' },
    { value: '32', label: 'ма' },
    { value: '64', label: 'ию' },
    { value: '47', label: 'ил' },
    { value: '44', label: 'ав' },
    { value: '22', label: 'се' },
    { value: '33', label: 'ок' },
    { value: '44', label: 'но' },
    { value: '55', label: 'де' },
  ],
  Культура: [
    { value: '25', label: 'ян' },
    { value: '36', label: 'фе' },
    { value: '74', label: 'ма' },
    { value: '12', label: 'ап' },
    { value: '42', label: 'ма' },
    { value: '63', label: 'ию' },
    { value: '63', label: 'ил' },
    { value: '21', label: 'ав' },
    { value: '53', label: 'се' },
    { value: '65', label: 'ок' },
    { value: '32', label: 'но' },
    { value: '62', label: 'де' },
  ],
  'Экономика и бизнес': [
    { value: '53', label: 'ян' },
    { value: '13', label: 'фе' },
    { value: '64', label: 'ма' },
    { value: '21', label: 'ап' },
    { value: '6', label: 'ма' },
    { value: '30', label: 'ию' },
    { value: '45', label: 'ил' },
    { value: '46', label: 'ав' },
    { value: '10', label: 'се' },
    { value: '32', label: 'ок' },
    { value: '74', label: 'но' },
    { value: '53', label: 'де' },
  ],
};
