export const theme: { [key: string]: { label: string; value: string }[] } = {
  Диспансеризация: [
    { value: '15', label: 'ян' },
    { value: '17', label: 'фе' },
    { value: '9', label: 'ма' },
    { value: '14', label: 'ап' },
    { value: '30', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '29', label: 'ил' },
    { value: '45', label: 'ав' },
    { value: '50', label: 'се' },
    { value: '22', label: 'ок' },
    { value: '14', label: 'но' },
    { value: '6', label: 'де' },
  ],
  'Наледь и сосульки на кровле': [
    { value: '40', label: 'ян' },
    { value: '35', label: 'фе' },
    { value: '20', label: 'ма' },
    { value: '5', label: 'ап' },
    { value: '1', label: 'ма' },
    { value: '0', label: 'ию' },
    { value: '0', label: 'ил' },
    { value: '0', label: 'ав' },
    { value: '0', label: 'се' },
    { value: '0', label: 'ок' },
    { value: '60', label: 'но' },
    { value: '70', label: 'де' },
  ],

  'Несоблюдение правил уборки проезжей части': [
    { value: '20', label: 'ян' },
    { value: '15', label: 'фе' },
    { value: '22', label: 'ма' },
    { value: '34', label: 'ап' },
    { value: '15', label: 'ма' },
    { value: '7', label: 'ию' },
    { value: '8', label: 'ил' },
    { value: '9', label: 'ав' },
    { value: '13', label: 'се' },
    { value: '17', label: 'ок' },
    { value: '33', label: 'но' },
    { value: '40', label: 'де' },
  ],
  'Уборка/Вывоз мусора': [
    { value: '25', label: 'ян' },
    { value: '30', label: 'фе' },
    { value: '14', label: 'ма' },
    { value: '29', label: 'ап' },
    { value: '44', label: 'ма' },
    { value: '60', label: 'ию' },
    { value: '45', label: 'ил' },
    { value: '36', label: 'ав' },
    { value: '29', label: 'се' },
    { value: '19', label: 'ок' },
    { value: '37', label: 'но' },
    { value: '13', label: 'де' },
  ],
  'Дети и многодетные семьи': [
    { value: '44', label: 'ян' },
    { value: '30', label: 'фе' },
    { value: '20', label: 'ма' },
    { value: '15', label: 'ап' },
    { value: '13', label: 'ма' },
    { value: '17', label: 'ию' },
    { value: '22', label: 'ил' },
    { value: '36', label: 'ав' },
    { value: '56', label: 'се' },
    { value: '34', label: 'ок' },
    { value: '22', label: 'но' },
    { value: '39', label: 'де' },
  ],
  'Образовательный процесс': [
    { value: '4', label: 'ян' },
    { value: '7', label: 'фе' },
    { value: '12', label: 'ма' },
    { value: '10', label: 'ап' },
    { value: '21', label: 'ма' },
    { value: '3', label: 'ию' },
    { value: '2', label: 'ил' },
    { value: '45', label: 'ав' },
    { value: '65', label: 'се' },
    { value: '30', label: 'ок' },
    { value: '25', label: 'но' },
    { value: '20', label: 'де' },
  ],
  'Строительство зданий': [
    { value: '8', label: 'ян' },
    { value: '5', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '10', label: 'ап' },
    { value: '14', label: 'ма' },
    { value: '38', label: 'ию' },
    { value: '35', label: 'ил' },
    { value: '60', label: 'ав' },
    { value: '55', label: 'се' },
    { value: '22', label: 'ок' },
    { value: '10', label: 'но' },
    { value: '3', label: 'де' },
  ],
  'Содержание остановок': [
    { value: '40', label: 'ян' },
    { value: '45', label: 'фе' },
    { value: '12', label: 'ма' },
    { value: '7', label: 'ап' },
    { value: '31', label: 'ма' },
    { value: '23', label: 'ию' },
    { value: '25', label: 'ил' },
    { value: '27', label: 'ав' },
    { value: '9', label: 'се' },
    { value: '18', label: 'ок' },
    { value: '33', label: 'но' },
    { value: '34', label: 'де' },
  ],
  'Содержание больниц': [
    { value: '63', label: 'ян' },
    { value: '60', label: 'фе' },
    { value: '56', label: 'ма' },
    { value: '43', label: 'ап' },
    { value: '22', label: 'ма' },
    { value: '30', label: 'ию' },
    { value: '28', label: 'ил' },
    { value: '23', label: 'ав' },
    { value: '44', label: 'се' },
    { value: '33', label: 'ок' },
    { value: '70', label: 'но' },
    { value: '67', label: 'де' },
  ],

  'Благоустройство придомовых территорий': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
};
