export const theme: { [key: string]: { label: string; value: string }[] } = {
  Диспансеризация: [
    { value: '15', label: 'ян' },
    { value: '17', label: 'фе' },
    { value: '9', label: 'ма' },
    { value: '14', label: 'ап' },
    { value: '30', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '29', label: 'ил' },
    { value: '45', label: 'ав' },
    { value: '50', label: 'се' },
    { value: '22', label: 'ок' },
    { value: '14', label: 'но' },
    { value: '6', label: 'де' },
  ],
  'Наледь и сосульки на кровле': [
    { value: '40', label: 'ян' },
    { value: '35', label: 'фе' },
    { value: '20', label: 'ма' },
    { value: '5', label: 'ап' },
    { value: '1', label: 'ма' },
    { value: '0', label: 'ию' },
    { value: '0', label: 'ил' },
    { value: '0', label: 'ав' },
    { value: '0', label: 'се' },
    { value: '0', label: 'ок' },
    { value: '60', label: 'но' },
    { value: '70', label: 'де' },
  ],

  'Несоблюдение правил уборки проезжей части': [
    { value: '20', label: 'ян' },
    { value: '15', label: 'фе' },
    { value: '22', label: 'ма' },
    { value: '34', label: 'ап' },
    { value: '15', label: 'ма' },
    { value: '7', label: 'ию' },
    { value: '8', label: 'ил' },
    { value: '9', label: 'ав' },
    { value: '13', label: 'се' },
    { value: '17', label: 'ок' },
    { value: '33', label: 'но' },
    { value: '40', label: 'де' },
  ],
  'Уборка/Вывоз мусора': [
    { value: '25', label: 'ян' },
    { value: '30', label: 'фе' },
    { value: '14', label: 'ма' },
    { value: '29', label: 'ап' },
    { value: '44', label: 'ма' },
    { value: '60', label: 'ию' },
    { value: '45', label: 'ил' },
    { value: '36', label: 'ав' },
    { value: '29', label: 'се' },
    { value: '19', label: 'ок' },
    { value: '37', label: 'но' },
    { value: '13', label: 'де' },
  ],
  'Дети и многодетные семьи': [
    { value: '44', label: 'ян' },
    { value: '30', label: 'фе' },
    { value: '20', label: 'ма' },
    { value: '15', label: 'ап' },
    { value: '13', label: 'ма' },
    { value: '17', label: 'ию' },
    { value: '22', label: 'ил' },
    { value: '36', label: 'ав' },
    { value: '56', label: 'се' },
    { value: '34', label: 'ок' },
    { value: '22', label: 'но' },
    { value: '39', label: 'де' },
  ],
  'Образовательный процесс': [
    { value: '4', label: 'ян' },
    { value: '7', label: 'фе' },
    { value: '12', label: 'ма' },
    { value: '10', label: 'ап' },
    { value: '21', label: 'ма' },
    { value: '3', label: 'ию' },
    { value: '2', label: 'ил' },
    { value: '45', label: 'ав' },
    { value: '65', label: 'се' },
    { value: '30', label: 'ок' },
    { value: '25', label: 'но' },
    { value: '20', label: 'де' },
  ],
  'Строительство зданий': [
    { value: '8', label: 'ян' },
    { value: '5', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '10', label: 'ап' },
    { value: '14', label: 'ма' },
    { value: '38', label: 'ию' },
    { value: '35', label: 'ил' },
    { value: '60', label: 'ав' },
    { value: '55', label: 'се' },
    { value: '22', label: 'ок' },
    { value: '10', label: 'но' },
    { value: '3', label: 'де' },
  ],
  'Содержание остановок': [
    { value: '40', label: 'ян' },
    { value: '45', label: 'фе' },
    { value: '12', label: 'ма' },
    { value: '7', label: 'ап' },
    { value: '31', label: 'ма' },
    { value: '23', label: 'ию' },
    { value: '25', label: 'ил' },
    { value: '27', label: 'ав' },
    { value: '9', label: 'се' },
    { value: '18', label: 'ок' },
    { value: '33', label: 'но' },
    { value: '34', label: 'де' },
  ],
  'Содержание больниц': [
    { value: '63', label: 'ян' },
    { value: '60', label: 'фе' },
    { value: '56', label: 'ма' },
    { value: '43', label: 'ап' },
    { value: '22', label: 'ма' },
    { value: '30', label: 'ию' },
    { value: '28', label: 'ил' },
    { value: '23', label: 'ав' },
    { value: '44', label: 'се' },
    { value: '33', label: 'ок' },
    { value: '70', label: 'но' },
    { value: '67', label: 'де' },
  ],
  'Благоустройство придомовых территорий': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Отлов безнадзорных собак и кошек': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  Беженцы: [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Ямы во дворах': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Предложение по благоустройству': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Борщевик Сосновского': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Парки и зоны отдыха': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Уборка территорий': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Благоустройство общественного пространства (парк, сквер, пешеходная зона, бульвар, набережная, центральная улица или площадь)':
    [
      { value: '14', label: 'ян' },
      { value: '23', label: 'фе' },
      { value: '6', label: 'ма' },
      { value: '32', label: 'ап' },
      { value: '35', label: 'ма' },
      { value: '40', label: 'ию' },
      { value: '46', label: 'ил' },
      { value: '49', label: 'ав' },
      { value: '21', label: 'се' },
      { value: '39', label: 'ок' },
      { value: '40', label: 'но' },
      { value: '56', label: 'де' },
    ],
  'Нарушение правил уборки от снега и наледи внутридворового проезда, тротуара, площади':
    [
      { value: '14', label: 'ян' },
      { value: '23', label: 'фе' },
      { value: '6', label: 'ма' },
      { value: '32', label: 'ап' },
      { value: '35', label: 'ма' },
      { value: '40', label: 'ию' },
      { value: '46', label: 'ил' },
      { value: '49', label: 'ав' },
      { value: '21', label: 'се' },
      { value: '39', label: 'ок' },
      { value: '40', label: 'но' },
      { value: '56', label: 'де' },
    ],
  'Ненадлежащее содержание зеленых насаждений (газонов)/деревьев и кустарников':
    [
      { value: '14', label: 'ян' },
      { value: '23', label: 'фе' },
      { value: '6', label: 'ма' },
      { value: '32', label: 'ап' },
      { value: '35', label: 'ма' },
      { value: '40', label: 'ию' },
      { value: '46', label: 'ил' },
      { value: '49', label: 'ав' },
      { value: '21', label: 'се' },
      { value: '39', label: 'ок' },
      { value: '40', label: 'но' },
      { value: '56', label: 'де' },
    ],
  'Вырубка деревьев, кустарников': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Открытые канализационные люки': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Разрушение тротуаров и пешеходных дорожек': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Отсутствие детских площадок': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Отсутствие урн, лавочек в общественных местах и дворовой территории': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Нарушение правил проведения земляных работ': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Нарушение правил уборки и вывоза порубочных остатков': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Обустройство асфальтового покрытия парковки, внутридворового проезда, тротуара, пешеходной дорожки, въезда во двор':
    [
      { value: '14', label: 'ян' },
      { value: '23', label: 'фе' },
      { value: '6', label: 'ма' },
      { value: '32', label: 'ап' },
      { value: '35', label: 'ма' },
      { value: '40', label: 'ию' },
      { value: '46', label: 'ил' },
      { value: '49', label: 'ав' },
      { value: '21', label: 'се' },
      { value: '39', label: 'ок' },
      { value: '40', label: 'но' },
      { value: '56', label: 'де' },
    ],
  'Нарушение правил уборки и вывоза загрязненного снега и наледи на газоне': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Ненадлежащее состояние игровых элементов на детской или спортивной площадке':
    [
      { value: '14', label: 'ян' },
      { value: '23', label: 'фе' },
      { value: '6', label: 'ма' },
      { value: '32', label: 'ап' },
      { value: '35', label: 'ма' },
      { value: '40', label: 'ию' },
      { value: '46', label: 'ил' },
      { value: '49', label: 'ав' },
      { value: '21', label: 'се' },
      { value: '39', label: 'ок' },
      { value: '40', label: 'но' },
      { value: '56', label: 'де' },
    ],
  'Подтопление территории': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Нарушение правил уборки внутридворового проезда, пешеходной дорожки': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Нарушение правил уборки от снега и наледи детской игровой и спортивной площадки':
    [
      { value: '14', label: 'ян' },
      { value: '23', label: 'фе' },
      { value: '6', label: 'ма' },
      { value: '32', label: 'ап' },
      { value: '35', label: 'ма' },
      { value: '40', label: 'ию' },
      { value: '46', label: 'ил' },
      { value: '49', label: 'ав' },
      { value: '21', label: 'се' },
      { value: '39', label: 'ок' },
      { value: '40', label: 'но' },
      { value: '56', label: 'де' },
    ],
  'Нарушение правил уборки от снега и наледи территории парка и сквера': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Неисправные фонари освещения': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Парковка на газонах': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Ненадлежащее состояние фасадов нежилых зданий, объектов и ограждений': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Отсутствие общественных туалетов': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Отсутствие фонарей освещения': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Самовольная установка ограждений на территории общего пользования': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Установка ограждений, препятствующих въезду на тротуар, газон на дворовой территории МКД':
    [
      { value: '14', label: 'ян' },
      { value: '23', label: 'фе' },
      { value: '6', label: 'ма' },
      { value: '32', label: 'ап' },
      { value: '35', label: 'ма' },
      { value: '40', label: 'ию' },
      { value: '46', label: 'ил' },
      { value: '49', label: 'ав' },
      { value: '21', label: 'се' },
      { value: '39', label: 'ок' },
      { value: '40', label: 'но' },
      { value: '56', label: 'де' },
    ],
  'Засор в общедомовой системе водоотведения (канализации)': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Затопление подъездов, подвальных помещений': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Несанкционированные надписи, рисунки, реклама на фасаде МКД': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Прорыв трубы/трубопровода': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Протечки с кровли (системы водостока)': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Дезинфекция МКД': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Другие проблемы с общедомовой системой водоотведения (канализации)': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Жалобы на управляющие компании': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Завышение платы за коммунальные услуги': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Залитие квартиры': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Неисправность выступающих конструкций: балконов, козырьков, эркеров, карнизов входных крылец и т. п.':
    [
      { value: '14', label: 'ян' },
      { value: '23', label: 'фе' },
      { value: '6', label: 'ма' },
      { value: '32', label: 'ап' },
      { value: '35', label: 'ма' },
      { value: '40', label: 'ию' },
      { value: '46', label: 'ил' },
      { value: '49', label: 'ав' },
      { value: '21', label: 'се' },
      { value: '39', label: 'ок' },
      { value: '40', label: 'но' },
      { value: '56', label: 'де' },
    ],
  'Некачественно выполненный ремонт дорог': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Некачественный капитальный ремонт': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Ненадлежащая уборка подъездов и лифтов': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Ненадлежащее качество или отсутствие отопления': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Ненадлежащее содержание и эксплуатация МКД': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Непригодные для проживания жилые помещения': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Низкая температура воды/слабое давление': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Отсутствие горячей воды': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Отсутствие холодной воды': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Отсутствие электричества': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Перепланировка и реконструкция помещений': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Плата за ЖКУ и работа ЕИРЦ': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Плохое качество воды': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Подключение к водоснабжению': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Ремонт подъездов': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Сборы за капитальный ремонт': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Информационно-техническая поддержка': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Нарушение правил очистки дорог от снега и наледи/Обращения о необходимости очистить тротуар от снега и наледи':
    [
      { value: '14', label: 'ян' },
      { value: '23', label: 'фе' },
      { value: '6', label: 'ма' },
      { value: '32', label: 'ап' },
      { value: '35', label: 'ма' },
      { value: '40', label: 'ию' },
      { value: '46', label: 'ил' },
      { value: '49', label: 'ав' },
      { value: '21', label: 'се' },
      { value: '39', label: 'ок' },
      { value: '40', label: 'но' },
      { value: '56', label: 'де' },
    ],
  'Некачественно нанесенная разметка на проезжей части': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Ливневые канализации (строительство и реконструкция)': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Нарушение технологии и (или) сроков производства работ': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Необходима установка и замена дорожных ограждений': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Несанкционированное ограничение движения, помехи движению, захват земли в полосе отвода автодорог':
    [
      { value: '14', label: 'ян' },
      { value: '23', label: 'фе' },
      { value: '6', label: 'ма' },
      { value: '32', label: 'ап' },
      { value: '35', label: 'ма' },
      { value: '40', label: 'ию' },
      { value: '46', label: 'ил' },
      { value: '49', label: 'ав' },
      { value: '21', label: 'се' },
      { value: '39', label: 'ок' },
      { value: '40', label: 'но' },
      { value: '56', label: 'де' },
    ],
  'Организация парковок': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Организация переходов, светофоров/Изменить организацию движения': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Освещение неисправно или отсутствует': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Подтопление автомобильных дорог': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Предложение дороги в план ремонта': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Предложить установку нового лежачего полицейского (ИДН)': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  Пробки: [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Работа светофора (установка, изменение режима работы, оборудование кнопкой вызова)':
    [
      { value: '14', label: 'ян' },
      { value: '23', label: 'фе' },
      { value: '6', label: 'ма' },
      { value: '32', label: 'ап' },
      { value: '35', label: 'ма' },
      { value: '40', label: 'ию' },
      { value: '46', label: 'ил' },
      { value: '49', label: 'ав' },
      { value: '21', label: 'се' },
      { value: '39', label: 'ок' },
      { value: '40', label: 'но' },
      { value: '56', label: 'де' },
    ],
  'Ремонт дороги': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Ремонт/строительство мостов': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Содержание дорожных знаков/Установка новых дорожных знаков, с внесением в схему дислокации, замена старых знаков на новые':
    [
      { value: '14', label: 'ян' },
      { value: '23', label: 'фе' },
      { value: '6', label: 'ма' },
      { value: '32', label: 'ап' },
      { value: '35', label: 'ма' },
      { value: '40', label: 'ию' },
      { value: '46', label: 'ил' },
      { value: '49', label: 'ав' },
      { value: '21', label: 'се' },
      { value: '39', label: 'ок' },
      { value: '40', label: 'но' },
      { value: '56', label: 'де' },
    ],
  'Содержание, ремонт и обустройство тротуаров': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Строительство или реконструкция дорог': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Ямы и выбоины на дороге': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Нестационарная торговля (киоски, павильоны, сезонная торговля)': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Оказание медицинской помощи не в полном объеме/отказ в оказании медицинской помощи':
    [
      { value: '14', label: 'ян' },
      { value: '23', label: 'фе' },
      { value: '6', label: 'ма' },
      { value: '32', label: 'ап' },
      { value: '35', label: 'ма' },
      { value: '40', label: 'ию' },
      { value: '46', label: 'ил' },
      { value: '49', label: 'ав' },
      { value: '21', label: 'се' },
      { value: '39', label: 'ок' },
      { value: '40', label: 'но' },
      { value: '56', label: 'де' },
    ],
  'Питание в медицинских учреждениях': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Просьбы о лечении': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Скорая помощь': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  Вакцинация: [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Здравоохранение прочее': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Нехватка или сокращение врачей и медицинских учреждений': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Нехватка материально-технического обеспечения': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Низкая заработная плата врачей': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Отсутствие аптек': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Отсутствие лекарств в аптеках': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Отсутствие лекарств в стационарах': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  Очередь: [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Ошибки врачей, халатность': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Предложения по созданию лечебных центров': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Профильный осмотр': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Социальная поддержка медперсонала': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Технические проблемы с записью на прием к врачу': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Хамство медицинских работников': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Отсутствие контейнерной площадки/Проезд к контейнерной площадке': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Стихийные свалки в городе/в парках/в лесу': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Выброс мусора нарушителем': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Льготные лекарства': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Плата за вывоз ТКО': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Проблемы с контейнерами': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Раздельная сортировка отходов': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Строительство объектов по обращению с отходами': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Повреждение опор ЛЭП': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Качество электроснабжения': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Аварийное жилье/переселение': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  Волонтерство: [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Задержка выплат гражданам': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Занятость и трудоустройство': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  Инвалиды: [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Матери-одиночки, подростки': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Оказание гос. соц. помощи': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Пенсионеры и ветераны': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Создание доступной среды для инвалидов': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Соц.обслуживание прочее': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Улучшение жилищных условий': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Безопасность образовательного процесса': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'ВУЗы и ССУЗы': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Выплаты стипендий': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Дистанционное образование': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Дополнительное образование': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'ЕГЭ, ОГЭ': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Зарплата учителей': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Кадровые перестановки': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Нехватка мест в школах': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Общее впечатление': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  Питание: [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Проблемы с отоплением детских садов и школ': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Содержание гос. образовательных организаций': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Социальная поддержка учителей': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Социальные учреждения': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Строительство школ, детских садов': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Устройство в ДОУ': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Восстановление газоснабжения': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Запрос на газификацию и её условия': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Сроки газификации': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Стоимость, оплата и возврат средств на газификацию': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Выбросы вредных веществ в атмосферу/загрязнение воздуха': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Государственные услуги': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  "МФЦ 'Мои документы'": [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'График движения общественного транспорта': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Добавить новый маршрут': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Изменение класса и количества автобусов': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Изменить или отменить маршрут': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Льготы на проезд и тарифы': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Некорректное поведение водительского состава': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Неудовлетворительные условия проезда в транспорте на действующем маршруте': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Отсутствие остановочных пунктов': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Пешеходные переходы и жд переезды': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Проблемы с социальными картами или проездными документами': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Доступность вакцин': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Жалобы на врачей': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  Коронавирус: [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Коронавирусные ограничения': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Порядок и пункты вакцинации': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Проблемы в работе горячих линий': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Самоизоляция и карантин': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Сертификаты и QR-коды': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Тесты на коронавирус': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Зарплата, компенсации, поощрения, выплаты': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Поддержка семей мобилизованных': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Обработка и уничтожение грызунов (дератизация)': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Санитарно-эпидемиологическое благополучие': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Памятники и объекты культурного наследия': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Погребение и похоронное дело': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Региональное имущество': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Ремонт спортивных учреждений': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Спортивные мероприятия': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Строительство спортивной инфраструктуры': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Состояние зданий учреждений и организаций': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Строительство социальных объектов': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  Спецпроекты: [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Учреждения культуры': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
  'Цены и ценообразование': [
    { value: '14', label: 'ян' },
    { value: '23', label: 'фе' },
    { value: '6', label: 'ма' },
    { value: '32', label: 'ап' },
    { value: '35', label: 'ма' },
    { value: '40', label: 'ию' },
    { value: '46', label: 'ил' },
    { value: '49', label: 'ав' },
    { value: '21', label: 'се' },
    { value: '39', label: 'ок' },
    { value: '40', label: 'но' },
    { value: '56', label: 'де' },
  ],
};
